#!/usr/bin/env bash

for file in $HOME/.bashrc.d/*.bashrc; do
  # shellcheck disable=SC1090
  source "$file"
done

PS1='
\[\e[32m\]\w \[\e[91m\]$(__git_ps1 "(%s)")
\[\e[94m\]❯  '

# shellcheck disable=SC2034
GIT_PS1_SHOWDIRTYSTATE=true

############################################################
# Environment variables
############################################################

export CODEPATH=$HOME/Code
export EDITOR=nvim
# Allows ignoring history by typing a space before a command
export HISTCONTROL=ignorespace
# Customizes what files fzf finds
export FZF_DEFAULT_COMMAND='ag -g "" --hidden --ignore "node_modules|.git"'

############################################################
# Modify the PATH
############################################################

PATH=$PATH:$HOME/Code/bin

############################################################
# Useful helper functions
############################################################


############################################################
# Additional Ansible-managed blocsk
############################################################

