- name: Check if brew is installed
  shell: command -V brew

- name: Gather brew prefix
  shell: brew --prefix
  register: brewprefix

- name: Set brew prefix fact
  set_fact:
    brew_prefix: "{{ brewprefix.stdout }}"

- name: Install useful tools (screen, fzf, ag...)
  homebrew:
    name:
    - screen
    - fzf
    - ag
    - shellcheck
    - git
    - python
    - node
    - neovim
    - autojump

# docker

- name: Install docker via homebrew if on mac
  homebrew:
    name: docker
  when: ansible_os_family == "Darwin"

- name: Install docker via apt if on ubuntu
  become: yes
  import_tasks: docker.yml
  when: ansible_os_family == 'Debian'

# git

- name: Acquiring git bash completion
  get_url:
    url: https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash
    dest: ~/.bashrc.d/git-completion.bashrc

- name: Acquiring git bash prompt
  get_url:
    url: https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh
    dest: ~/.bashrc.d/git-prompt.bashrc

- name: Copying gitconfig
  copy:
    src: gitconfig
    dest: ~/.gitconfig

# screen

- name: Copying screenrc
  copy:
    src: screenrc
    dest: ~/.screenrc

# neovim

- name: Install neovim python plugin
  pip:
    name: neovim
    executable: pip3

- name: Install typescript
  npm:
    name: typescript
    global: yes


- name: Setup neovim directory
  file:
    name: ~/.config/nvim/
    state: directory

- name: Setup neovim configs
  copy:
    src: neovim
    dest: ~/.config/nvim/init.vim

- name: Setup plug directory
  file:
    path: ~/.local/share/nvim/site/autoload/
    state: directory

- name: Setup plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: ~/.local/share/nvim/site/autoload/plug.vim

- name: Setup neovim
  shell: |
    source ~/.bashrc
    nvim +PlugInstall +UpdateRemotePlugins +qall
  args:
    executable: /bin/bash

# autojump configuration

- name: Sourcing autojump in bashrc
  blockinfile:
    path: ~/.bashrc
    marker: "# {mark} ANSIBLE - autojump"
    content: source {{ brew_prefix }}/share/autojump/autojump.bash
